services:
  discord-bot:
    build: .
    container_name: media-downloader-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      # Save downloads persistently in a hosted folder (in case OS cleanup skips a beat)
      - ./downloads:/app/downloads
      - ./config.json:/app/config.json
      - ./.env:/app/.env
      - ./cookies.txt:/app/cookies.txt
